-- Create configurations table
CREATE TABLE IF NOT EXISTS public.configurations (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create allowed_channels table
CREATE TABLE IF NOT EXISTS public.allowed_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL UNIQUE,
    name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create memories table
CREATE TABLE IF NOT EXISTS public.memories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    role TEXT NOT NULL, -- 'user' or 'assistant'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default system instruction
INSERT INTO public.configurations (key, value)
VALUES ('system_instructions', 'You are a helpful assistant.')
ON CONFLICT (key) DO NOTHING;
